### ISSUE TITLE
ddclient or other dynamic DNS in intel edison with YOCTO

### ISSUE THREAD

**Issue by ghost** [alext-mkrs/meta-alext-edison#2]
About this site: http://cgit.openembedded.org/openembedded/tree/recipes/ddclient/ddclient_3.6.3.bb
I install everything via opkg and ddclient worked.

Now I have this error:

root@neuberfran: ddclient
~# WARNING:  file /var/cache/ddclient/ddclient.cache, line 3: Invalid Value for keyword 'ip' = ''

The other solution is this: http://mkaczanowski.com/golang-build-dynamic-dns-service-go/
But I have error with NSUPDATE package
root@neuberfran:~# opkg install nsupdate
Unknown package 'nsupdate'.
Collected errors:
opkg_install_cmd: Cannot install package nsupdate

**Comment by alext-mkrs** [comment]
Sorry, I don't understand that - what it is that you want me to do here?

**Comment by ghost** [comment]
https://communities.intel.com/message/363379#363379

I need your help to instal nsupdate or resolve errors with ddclient. I can't change my yocto-image-intel edison version(I don't know if this alone would solve) because I have very much software in C++ installed. To install NSUPDATE (http://mkaczanowski.com/golang-build-dynamic-dns-service-go/) suffice fix errors:

root@neuberfran:~# opkg install nsupdate
Unknown package 'nsupdate'.
Collected errors:
opkg_install_cmd: Cannot install package nsupdate

I see: "nsupdate to push updates on records. It is a part of the bind project, so it can be found in bind-tools or bind-clientpackages."

root@neuberfran:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=53 time=55.101 ms
64 bytes from 8.8.8.8: seq=1 ttl=53 time=32.649 ms
64 bytes from 8.8.8.8: seq=2 ttl=53 time=32.983 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 32.649/40.244/55.101 ms
root@neuberfran:~# opkg install bind-client
Unknown package 'bind-client'.
Collected errors:
- opkg_install_cmd: Cannot install package bind-client.
  root@neuberfran:~# opkg install bind-tools
  Unknown package 'bind-tools'.
  Collected errors:
- opkg_install_cmd: Cannot install package bind-tools.

**Comment by alext-mkrs** [comment]
the errors you post are not "errors" in a normal sense - they just mean there is no such package in the repo. If you want me to add those to the repo, let's summarize which exact ones do you need, because you mentioned several in various contexts.

But really that ddclient error just looks as a configuration one - and you just need to configure it properly, by either finding a guide on the Internet, or contacting the authors.

**Comment by alext-mkrs** [comment]
@neuberfran, is this still actual? If yes, please specify which packages you're interested in and I'll see what I can do.

**Comment by ghost** [comment]
@alext-mkrs , Thank's  for answering

There are several DDNS that may be worked for intel edison with yocto image:

NSUPDATE: https://github.com/nsupdate-info/nsupdate.info
and
https://nsupdateinfo.readthedocs.org/en/latest/admin.html#installation-for-development-testing

INADYN: https://github.com/troglobit/inadyn

I'm prefer DDCLIENT. In this issue:
https://communities.intel.com/message/370016#370016
I'm talk about errors to install DDCLIENT in intel edison

**Comment by alext-mkrs** [comment]
ddclient 3.8.3 package was added to the repo.

**Comment by ghost** [comment]
**_root@neuberfran:~/example/server# opkg install ddclient_**
Unknown package 'ddclient'.
Collected errors:
- opkg_install_cmd: Cannot install package ddclient.
  root@neuberfran:~/example/server# opkg install ddclient 3.8.3
  Unknown package 'ddclient'.
  Unknown package '3.8.3'.
  Collected errors:
- opkg_install_cmd: Cannot install package ddclient.
- opkg_install_cmd: Cannot install package 3.8.3.
  root@neuberfran:~/example/server# opkg install ddclient
  Unknown package 'ddclient'.
  Collected errors:
- opkg_install_cmd: Cannot install package ddclient.
  **_root@neuberfran:~/example/server# ping google.com_**
  PING google.com (216.58.222.110): 56 data bytes
  64 bytes from 216.58.222.110: seq=0 ttl=50 time=148.205 ms
  64 bytes from 216.58.222.110: seq=1 ttl=50 time=149.304 ms
  ^C
  --- google.com ping statistics ---
  3 packets transmitted, 2 packets received, 33% packet loss
  round-trip min/avg/max = 148.205/148.754/149.304 ms
  **_root@neuberfran:~/example/server# opkg install ddclient 3.8.3_**
  Unknown package 'ddclient'.
  Unknown package '3.8.3'.
  Collected errors:
- opkg_install_cmd: Cannot install package ddclient.
- opkg_install_cmd: Cannot install package 3.8.3.

**Comment by alext-mkrs** [comment]
Have you configured your opkg according to instructions here: http://alextgalileo.altervista.org/edison-package-repo-configuration-instructions.html?

If yes, try running `opkg update` and then `opkg install ddclient`. No need to add "3.8.3" to the `opkg` command line. If that still fails, please show what `opkg update` displays.

**Comment by neuberfran** [comment]
Thank's

**Comment by ghost** [comment]
_**root@neuberfran:~# opkg update**_
Downloading http://repo.opkg.net/edison/repo/all/Packages.gz.
Inflating http://repo.opkg.net/edison/repo/all/Packages.gz.
Updated list of available packages in /var/lib/opkg/all.
Downloading http://repo.opkg.net/edison/repo/edison/Packages.gz.
Inflating http://repo.opkg.net/edison/repo/edison/Packages.gz.
Updated list of available packages in /var/lib/opkg/edison.
Downloading http://repo.opkg.net/edison/repo/core2-32/Packages.gz.
Inflating http://repo.opkg.net/edison/repo/core2-32/Packages.gz.
Updated list of available packages in /var/lib/opkg/core2-32.
Downloading http://iotdk.intel.com/repos/2.0/intelgalactic/Packages.
Updated list of available packages in /var/lib/opkg/iotkit.

**root@neuberfran:~# opkg install ddclient** 
Uknown package 'ddclient'.
Collected errors:
- opkg_install_cmd: Cannot install package ddclient.
  root@neuberfran:~#

**Comment by alext-mkrs** [comment]
Long time no see :smiley: Well, apparently ddclient didn't make it to the Release 3.0-based repo, which is the current one. I'm currently working on rebasing it to 3.5 one, I'll add ddclient back there.

**Comment by alext-mkrs** [comment]
The package is now in the repo again.
