### ISSUE TITLE
Possible to add pac7302 drivers?

### ISSUE THREAD

**Issue by kennethkalmer** [alext-mkrs/meta-alext-edison#3]
If I have this right, the driver is supported upstream (https://github.com/instantinfrastructure/linux-yocto-3.10/blob/master/Documentation/video4linux/gspca.txt#L267-L283). I'm trying to just play around with an old Genius webcam that is only supported by the pac7302 driver.

Alternatively, is there a guide on how to build the modules and test them out before submitting issues/pull requests?

Thanks for all these modules!

**Comment by alext-mkrs** [comment]
If that's available in that kernel version, it should be fairly easy to add, I'll check this out.

Generally, the Edison's BSP build guide is the instruction, it describes the steps necessary to setup the build env, which is the biggest thing. And then it has a section about adding/modifying recipes. I've also described the process in my blog at alextgalileo.altervista.org, for Galileo, but it's very similar for Edison.

**Comment by alext-mkrs** [comment]
I've added pac7302 module to the repo, enjoy :smiley:

**Comment by kennethkalmer** [comment]
Thanks for the efforts!
