### ISSUE TITLE
Add smsc95xx device driver for kernel 3.10.98

### ISSUE THREAD

**Issue by mzavatta** [alext-mkrs/meta-alext-edison#4]
Kindly requesting if it's possible to add smsc95xx driver to the repo for latest kernel 3.10.98.
Thanks in advance.

**Comment by mzavatta** [comment]
To my understanding it should be already available in mainstream kernel 3.10.x and its config file. It would make it easy to add Ethernet capability to Edison in custom boards with LANxxxx ICs from Microchip.

**Comment by alext-mkrs** [comment]
Yep, it's available there and I think I should be able to add it for you this weekend. I'll post here when done.

**Comment by alext-mkrs** [comment]
The package is available in the repo, direct link: http://repo.opkg.net/edison/repo/edison/kernel-module-smsc95xx_1.0-r2_edison.ipk (but `opkg update && opkg install <...>` is a better idea).

**Comment by mzavatta** [comment]
Thank you very much. I'm trying it out on our custom board and it is working so far. For the record, I'm using a clean 3.5 image just flashed on the Edison and then simply installed your kernel-module-smsc95xx. I'll let you know the progress. Thanks again.

**Comment by alext-mkrs** [comment]
My pleasure and thanks for elaborating, it's always interesting to know what people do with those pieces you supply :-)
